### ISSUE TITLE
FIPS 202, SHA-3 Permutation-Based Hash and Extendable-Output Functions has been included/cited

### ISSUE THREAD

**Issue by paulidale** [openssl/project#333] opened 2023-11-13 22:39 UTC
Nothing to do here, #331 covers the actual work required.

Page i in introduction

**Comment by slontis** [comment] 2023-12-21 04:00
PR is included in the linked item

**Comment by arapov** [comment] 2024-01-18 20:32
Dupe of #331

**Closed** 2024-01-18 20:34 UTC
Labels: FIPS
