### ISSUE TITLE
ANSI X9.62 was removed

### ISSUE THREAD

**Issue by paulidale** [openssl/project#320] opened 2023-11-13 21:50 UTC
We need to check references to X9.62 and confirm that the process is the same with the new standard.

If there are differences, we need to fix them.
If there are things not relevant, we need to remove them.
Also update documentation.

Confirm that ECDSA specifications haven't changed in #321

**Comment by arapov** [comment] 2024-01-18 20:47
Dupe of #321

**Closed by arapov** 2024-01-18 20:47 UTC
Labels: FIPS
