### ISSUE TITLE
Write up work practices for large features

### ISSUE THREAD

**Issue by hlandau** [openssl/project#347] opened 2023-11-15 09:52 UTC
- Write up some of the work practices I pioneered when developing QUIC MVP for 3.2
- Compare with the project's historical work practices
- Ideally talk to some of the others before I do this to understand historical work practices and the context of how I approached QUIC MVP

Not currently prioritised

**Comment by arapov** [comment] 2024-01-08 14:12
dupe of #174

**Closed by arapov** 2024-01-08 14:12 UTC
Labels: documentation
